Set-StrictMode -Version Latest

function Get-ProductDataPaths {
  param([Parameter(Mandatory)][string]$ProjectRoot)

  $dataDir = Join-Path $ProjectRoot 'assets\data'
  if (-not (Test-Path -LiteralPath $dataDir)) {
    New-Item -ItemType Directory -Force -Path $dataDir | Out-Null
  }

  return [ordered]@{
    Json = Join-Path $dataDir 'products.generated.json'
    Js = Join-Path $dataDir 'products.generated.js'
  }
}

function Read-ProductStore {
  param([Parameter(Mandatory)][string]$ProjectRoot)

  $paths = Get-ProductDataPaths -ProjectRoot $ProjectRoot
  if (-not (Test-Path -LiteralPath $paths.Json)) {
    return @()
  }

  try {
    $raw = Get-Content -LiteralPath $paths.Json -Raw
    if ([string]::IsNullOrWhiteSpace($raw)) { return @() }
    $items = $raw | ConvertFrom-Json
    if ($null -eq $items) { return @() }
    foreach ($item in @($items)) {
      if ($null -ne $item) { Write-Output $item }
    }
  } catch {
    throw "Could not read product data store: $($paths.Json). $($_.Exception.Message)"
  }
}

function Get-ProductStoreIndex {
  param([Parameter(Mandatory)][AllowEmptyCollection()][array]$Products)

  $index = @{}
  foreach ($product in $Products) {
    if ($product -is [array]) {
      foreach ($nestedProduct in $product) {
        $number = Normalize-ProductNumber ([string]$nestedProduct.number)
        if (-not [string]::IsNullOrWhiteSpace($number)) {
          $index[$number] = $nestedProduct
        }
      }
      continue
    }
    $number = Normalize-ProductNumber ([string]$product.number)
    if (-not [string]::IsNullOrWhiteSpace($number)) {
      $index[$number] = $product
    }
  }
  return $index
}

function New-ProductRecord {
  param(
    [Parameter(Mandatory)][System.Collections.IDictionary]$Parsed,
    [Parameter(Mandatory)][System.IO.FileInfo]$SourceFile,
    [Parameter(Mandatory)][string]$ProjectRoot,
    [Parameter(Mandatory)][string]$ImageRelativePath,
    [Parameter(Mandatory)][string]$SourceRelativePath
  )

  $number = Normalize-ProductNumber $Parsed.ProductNumber
  $now = (Get-Date).ToString('s')

  return [ordered]@{
    id = $number
    number = $number
    name = [string]$Parsed.ProductName
    category = [string]$Parsed.Category
    description = [string]$Parsed.Description
    application = ''
    brand = 'Imported catalogue'
    availability = 'Ready stock'
    image = $ImageRelativePath
    specifications = $Parsed.Specifications
    specs = @($Parsed.SpecLabels)
    confidence = [int]$Parsed.Confidence
    source = [ordered]@{
      type = 'whatsapp-image'
      originalFile = $SourceFile.Name
      originalPath = $SourceRelativePath
      ocrText = [string]$Parsed.CleanText
      importedAt = $now
    }
  }
}

function Copy-ProductImage {
  param(
    [Parameter(Mandatory)][System.IO.FileInfo]$SourceFile,
    [Parameter(Mandatory)][string]$ProjectRoot,
    [Parameter(Mandatory)][string]$ProductNumber,
    [switch]$DryRun
  )

  $imageDir = Join-Path $ProjectRoot 'assets\img\products'
  if (-not (Test-Path -LiteralPath $imageDir)) {
    New-Item -ItemType Directory -Force -Path $imageDir | Out-Null
  }

  $stem = ConvertTo-SafeFileStem $ProductNumber
  $extension = $SourceFile.Extension.ToLowerInvariant()
  if ([string]::IsNullOrWhiteSpace($extension)) { $extension = '.jpg' }

  $target = Join-Path $imageDir "$stem$extension"
  if (-not $DryRun) {
    if (-not (Test-Path -LiteralPath $target)) {
      Copy-Item -LiteralPath $SourceFile.FullName -Destination $target -Force
    }
  }

  return [ordered]@{
    FullPath = $target
    RelativePath = (Get-RelativeProjectPath -ProjectRoot $ProjectRoot -Path $target)
  }
}

function Save-ProductStore {
  param(
    [Parameter(Mandatory)][string]$ProjectRoot,
    [Parameter(Mandatory)][AllowEmptyCollection()][array]$Products,
    [Parameter(Mandatory)][hashtable]$RunSummary,
    [switch]$DryRun
  )

  $paths = Get-ProductDataPaths -ProjectRoot $ProjectRoot
  $sortedProducts = @($Products | Sort-Object -Property category, name, number)
  if ($sortedProducts.Count -eq 0) {
    $json = '[]'
  } else {
    $json = ConvertTo-Json -InputObject @($sortedProducts) -Depth 30
  }

  $meta = [ordered]@{
    generatedAt = (Get-Date).ToString('s')
    totalProducts = $sortedProducts.Count
    importedThisRun = [int]$RunSummary.Imported
    skippedDuplicates = [int]$RunSummary.Duplicates
    needsReview = [int]$RunSummary.Review
    source = 'whatsapp-import'
  }

  $js = @(
    '/* Auto-generated by scripts/import-whatsapp-products.ps1. Do not edit by hand. */'
    "window.NAE_IMPORTED_PRODUCTS = $json;"
    "window.NAE_IMPORT_META = $(($meta | ConvertTo-Json -Depth 10));"
  ) -join "`r`n"

  if (-not $DryRun) {
    $json | Set-Content -LiteralPath $paths.Json -Encoding UTF8
    $js | Set-Content -LiteralPath $paths.Js -Encoding UTF8
  }

  return [ordered]@{
    Json = $paths.Json
    Js = $paths.Js
    Count = $sortedProducts.Count
  }
}
